import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation files
const translations = {
  en: {
    // Common
    "civicare": "Civicare",
    "civicReportingPlatform": "Civic Reporting Platform",
    "yourVoice": "Your Voice for a Better Community",
    "reportIssue": "Report Issue",
    "browseIssues": "Browse Issues",
    "viewDetails": "View Details",
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "cancel": "Cancel",
    "save": "Save",
    "submit": "Submit",
    "search": "Search",
    "filter": "Filter",
    "sort": "Sort",
    "status": "Status",
    "date": "Date",
    "location": "Location",
    "description": "Description",
    "category": "Category",
    "actions": "Actions",

    // Navigation
    "home": "Home",
    "dashboard": "Dashboard",
    "myComplaints": "My Complaints",
    "communityComplaints": "Community Complaints",
    "complaintsMap": "Complaints Map",
    "analytics": "Analytics",
    "admin": "Admin",
    "login": "Login",
    "signup": "Sign Up",
    "logout": "Logout",

    // Landing Page
    "welcomeMessage": "Welcome to Civicare",
    "heroTitle": "Your Voice for a Better Community",
    "heroSubtitle": "Report civic issues instantly with photo evidence and GPS location. Track progress in real-time and help build a cleaner, safer neighborhood for everyone.",
    "trustedBy": "Trusted by 50,000+ Citizens",
    "photoEvidence": "Photo Evidence",
    "photoEvidenceDesc": "Capture and upload images for faster resolution",
    "gpsLocation": "GPS Location",
    "gpsLocationDesc": "Precise location tracking for accurate reporting",
    "realTimeUpdates": "Real-time Updates",
    "realTimeUpdatesDesc": "Get notified when your issue is resolved",
    "reportAnIssue": "Report an Issue",
    "browseReports": "Browse Reports",
    "viewAllReports": "View All Reports",

    // Dashboard
    "welcomeBack": "Welcome back",
    "studentDashboard": "Student Dashboard",
    "citizenDashboard": "Citizen Dashboard",
    "totalComplaints": "Total Complaints",
    "pending": "Pending",
    "inProgress": "In Progress",
    "resolved": "Resolved",
    "thisWeek": "This Week",
    "quickActions": "Quick Actions",
    "issueMap": "Issue Map",
    "awaitingResponse": "Awaiting response",
    "beingAddressed": "Being addressed",
    "resolutionRate": "resolution rate",
    "trackIssues": "Track your issues and stay informed about community matters",
    "emailRequired": "Email is required",
    "invalidEmail": "Please enter a valid email address",
    "passwordRequired": "Password is required",
    "invalidCredentials": "Invalid email or password. Please check your credentials and try again.",
    "connectionError": "Cannot connect to authentication service. Your Supabase project may be paused or inactive. Please check your Supabase dashboard and resume your project if needed.",
    "signinError": "An error occurred during sign in. Please try again.",
    "signInMessage": "Please sign in to your account.",
    "demoAccounts": "Demo Accounts (Click to use):",
    "adminAccount": "Admin Account",
    "citizenAccount": "Citizen Account",
    "emailAddress": "Email Address",
    "enterEmail": "Enter your email",
    "enterPassword": "Enter your password",
    "signingIn": "Signing In...",
    "copyErrorMessage": "Copy error message",
    "dontHaveAccount": "Don't have an account?",
    "signUpHere": "Sign up here",
    "termsAgreement": "By signing in, you agree to our terms of service and privacy policy.",
    "citizen": "Citizen",
    "citizenDescription": "Report and track community issues",
    "departmentManager": "Department Manager",
    "departmentManagerDescription": "Manage departmental issues",
    "fullNameRequired": "Full name is required",
    "fullNameMinLength": "Full name must be at least 2 characters",
    "passwordMinLength": "Password must be at least 6 characters",
    "confirmPasswordRequired": "Please confirm your password",
    "passwordsDoNotMatch": "Passwords do not match",
    "invalidPhoneNumber": "Please enter a valid phone number",
    "roleRequired": "Please select your role",
    "userAlreadyExists": "An account with this email already exists. Please sign in instead.",
    "signupError": "An error occurred during sign up. Please try again.",
    "accountCreationFailed": "Account creation failed. Please try again.",
    "accountCreatedSigningIn": "🎉 Account created successfully! Signing you in...",
    "accountCreatedPleaseSignIn": "🎉 Account created successfully! Please sign in with your credentials.",
    "accountCreatedRedirecting": "🎉 Account created successfully! Redirecting to your dashboard...",
    "accountCreatedCheckEmail": "🎉 Account created successfully! Please check your email to confirm your account before signing in.",
    "unexpectedError": "An unexpected error occurred. Please try again.",
    "createAccount": "Create Account",
    "joinCivicHub": "Join CivicHub to report and track community issues.",
    "fullName": "Full Name",
    "enterFullName": "Enter your full name",
    "emailAddress": "Email Address",
    "enterEmail": "Enter your email",
    "password": "Password",
    "createPassword": "Create a password",
    "confirmPassword": "Confirm Password",
    "confirmYourPassword": "Confirm your password",
    "phoneNumberOptional": "Phone Number (Optional)",
    "accountType": "Account Type",
    "chooseAccountType": "Choose your account type based on your role in the community",
    "smsUpdates": "We'll send SMS updates about your reports",
    "success": "Success!",
    "signUpError": "Sign Up Error",
    "copyErrorMessage": "Copy error message",
    "creatingAccount": "Creating Account...",
    "alreadyHaveAccount": "Already have an account?",
    "signInHere": "Sign in here",
    "termsAgreement": "By creating an account, you agree to our terms of service and privacy policy.",

    // Status
    "submitted": "Submitted",
    "inReview": "In Review",
    "assigned": "Assigned",
    "resolved": "Resolved",
    "closed": "Closed",
    "rejected": "Rejected",

    // Categories
    "roads": "Roads",
    "sanitation": "Sanitation",
    "utilities": "Utilities",
    "infrastructure": "Infrastructure",
    "safety": "Safety",
    "environment": "Environment",
    "other": "Other",

    // Login/Signup
    "signIn": "Sign In",
    "signUp": "Sign Up",
    "email": "Email",
    "password": "Password",
    "confirmPassword": "Confirm Password",
    "fullName": "Full Name",
    "forgotPassword": "Forgot Password?",
    "dontHaveAccount": "Don't have an account?",
    "alreadyHaveAccount": "Already have an account?",
    "signInHere": "Sign in here",
    "createAccount": "Create Account",

    // Footer
    "aboutUs": "About Us",
    "contactUs": "Contact Us",
    "privacyPolicy": "Privacy Policy",
    "termsOfService": "Terms of Service",
    "helpCenter": "Help Center",
    "allRightsReserved": "All rights reserved.",
    "madeWithLove": "Made with ❤️ for Indian Citizens",

    // Map
    "mapInstructions": "Map Instructions",
    "clickMarker": "Click on any marker to view complaint details",
    "markersColored": "Markers are color-coded by complaint status",
    "gpsShown": "GPS coordinates are shown for each complaint",
    "complaintsWithoutLocation": "Complaints without location data are listed below",

    // Search and Filter
    "searchComplaints": "Search Complaints",
    "searchByTitle": "Search by title, description, or location...",
    "filterByStatus": "Filter by Status",
    "allStatus": "All Status",
    "sortBy": "Sort By",
    "newestFirst": "Newest First",
    "oldestFirst": "Oldest First",
    "byStatus": "By Status",
    "byTitle": "By Title",

    // Empty States
    "noComplaints": "No complaints yet",
    "noComplaintsDesc": "Start by reporting your first civic issue to make a difference in your community.",
    "noComplaintsMatch": "No complaints match your filters",
    "tryAdjustingFilters": "Try adjusting your search or filter criteria.",
    "reportFirstIssue": "Report Your First Issue",

    // GPS
    "gpsCoordinates": "GPS Coordinates",
    "latitude": "Latitude",
    "longitude": "Longitude",

    // Time
    "justNow": "Just now",
    "hoursAgo": "h ago",
    "daysAgo": "d ago",
    "weeksAgo": "w ago",

    // Stats
    "communityImpact": "Community Impact",
    "issuesReported": "Issues Reported",
    "issuesResolved": "Issues Resolved",
    "resolutionRate": "Resolution Rate",
    "activeCitizens": "Active Citizens",

    // Trust Signals
    "trustedCertified": "Trusted & Certified Platform",
    "governmentCertified": "Officially recognized and certified by government authorities",
    "bestCivicApp": "Best Civic App 2024",
    "userReviews": "Based on 10,000+ user reviews",
    "isoCertified": "ISO 27001 Certified",
    "securityManagement": "Information security management",
    "uptime": "99.9% Uptime",
    "reliableService": "Reliable 24/7 service availability",
    "whatCitizensSay": "What Citizens Say",
    "realFeedback": "Real feedback from residents and officials",
    "dataSafeSecure": "Your Data is Safe & Secure",
    "securityProtocols": "We follow strict data protection protocols",
    "verifiedSecure": "Verified Secure",
    "regularAudits": "Regular security audits and penetration testing",

    // Language
    "language": "Language",
    "english": "English",
    "hindi": "हिंदी",
    "switchToHindi": "Switch to Hindi",
    "switchToEnglish": "Switch to English",

    // Issue Reporting Form
    "reportAnIssue": "Report an Issue",
    "reportAnIssueSubtitle": "Help improve your community by reporting civic issues",
    "capturingYourLocation": "📍 Capturing Your Location",
    "detectingCurrentLocation": "We're automatically detecting your current location to make reporting easier. This helps authorities respond faster to your issue.",
    "gpsCoordinatesCaptured": "✅ GPS Coordinates Captured",
    "locationDetectedMessage": "Your current location coordinates have been automatically detected. Please enter the detailed address in the location section below.",
    "anonymousReporting": "Anonymous Reporting",
    "anonymousReportingMessage": "You're reporting anonymously. Consider signing in to track your report status and receive updates.",
    "signingIn": "signing in",
    "submissionError": "Submission Error",
    "issueTitle": "Issue Title",
    "issueTitlePlaceholder": "Brief, descriptive title for the issue",
    "issueTitleDescription": "Provide a clear, concise title that summarizes the issue",
    "issueDescription": "Issue Description",
    "issueDescriptionPlaceholder": "Provide detailed description of the issue, including when it started, how it affects you, and any other relevant information...",
    "priorityLevel": "Priority Level",
    "lowPriority": "Low",
    "mediumPriority": "Medium",
    "highPriority": "High",
    "lowPriorityDesc": "Non-urgent issue",
    "mediumPriorityDesc": "Moderate concern",
    "highPriorityDesc": "Urgent attention needed",
    "contactInformation": "Contact Information",
    "fullName": "Full Name",
    "fullNamePlaceholder": "Your full name",
    "emailAddress": "Email Address",
    "emailPlaceholder": "your.email@example.com",
    "phoneNumber": "Phone Number",
    "phonePlaceholder": "+1 (555) 123-4567",
    "smsUpdates": "We'll send SMS updates about your report status",
    "submitReport": "Submit Report",
    "submittingReport": "Submitting Report...",
    "saveDraft": "Save Draft",
    "savingDraft": "Saving...",
    "cancel": "Cancel",
    "reportSubmittedSuccessfully": "🎉 Report Submitted Successfully!",
    "reportSubmittedMessage": "Your issue has been submitted and is being reviewed. You'll receive WhatsApp and SMS updates about the progress.",
    "whatsappConfirmation": "WhatsApp confirmation sent to your registered number",
    "reportIdLabel": "Report ID:",
    "redirectingToReports": "Redirecting to reports list...",
    "draftSaved": "Draft saved successfully!",
    "draftSaveFailed": "Failed to save draft. Please try again.",
    "validationCategoryRequired": "Please select an issue category",
    "validationTitleRequired": "Issue title is required",
    "validationTitleMinLength": "Title should be at least 10 characters long",
    "validationDescriptionRequired": "Issue description is required",
    "validationDescriptionMinLength": "Description should be at least 20 characters long",
    "validationLocationRequired": "Location address is required (even with GPS coordinates)",
    "validationContactNameRequired": "Contact name is required",
    "validationContactEmailRequired": "Contact email is required",
    "validationContactEmailInvalid": "Please enter a valid email address",
    "validationContactPhoneRequired": "Contact phone is required",
    "submissionFailed": "Failed to submit report. Please try again.",
    "unexpectedError": "An unexpected error occurred. Please try again.",

    // Complaints and Reports
    "myComplaints": "My Complaints",
    "trackSubmittedIssues": "Track and manage all your submitted issues",
    "searchComplaints": "Search Complaints",
    "searchByTitleDescLocation": "Search by title, description, or location...",
    "filterByStatus": "Filter by Status",
    "allStatus": "All Status",
    "issueId": "Issue ID",
    "titleAndLocation": "Title & Location",
    "view": "View",
    "noComplaintsFound": "No Complaints Found",
    "noComplaintsMessageFiltered": "No complaints match your current search criteria. Try adjusting your filters.",
    "noComplaintsMessageEmpty": "You haven't submitted any complaints yet. Start by reporting an issue in your community.",
    "showingXOfYComplaints": "Showing {countShown} of {total} complaints",
    "loadingComplaints": "Loading your complaints...",
    "communityComplaints": "Community Complaints",
    "exploreCommunityIssues": "Explore and stay informed about issues in your community",
    "searchCommunityIssues": "Search Community Issues",
    "allCategories": "All Categories",
    "water": "Water",
    "electricity": "Electricity",
    "open": "Open",
    "noCommunityComplaintsFound": "No Community Complaints Found",
    "noCommunityMessageFiltered": "No complaints match your current search criteria. Try adjusting your filters to see more results.",
    "noCommunityMessageEmpty": "There are no community complaints to display at the moment.",
    "showingXCommunityComplaints": "Showing {count} community complaints",
    "loadingCommunityComplaints": "Loading community complaints...",
    "publicReports": "Public Reports",
    "browseCommunityIssues": "Browse and track community issues reported by residents",
    "totalReports": "Total Reports",
    "grid": "Grid",
    "map": "Map",
    "noReportsFound": "No Reports Found",
    "noReportsMessageFiltered": "Try adjusting your filters to see more results.",
    "noReportsMessageEmpty": "No reports have been submitted yet.",
    "reportAnIssue": "Report an Issue",
    "issueNotFound": "Issue Not Found",
    "issueNotFoundMessage": "The issue you are looking for does not exist or has been removed.",
    "goBack": "Go Back",
    "browseAllReports": "Browse All Reports",
    "description": "Description",
    "images": "Images",
    "updates": "Updates",
    "location": "Location",
    "reporter": "Reporter",
    "assignedDepartment": "Assigned Department",
    "shareIssue": "Share Issue",
    "reportSimilarIssue": "Report Similar Issue",
    "home": "Home",
    "reports": "Reports",
    "issueDetails": "Issue Details",
    "imageNotAvailable": "Image Not Available",
    "uploaded": "Uploaded",
    "priority": "Priority",
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "critical": "Critical",
    "sortBy": "Sort By",
    "newest": "Newest",
    "oldest": "Oldest",
    "mostVoted": "Most Voted",
    "loadingReports": "Loading reports...",
    "errorLoadingReports": "Error Loading Reports",
    "viewDetails": "View Details"
  },
  hi: {
    // Common
    "civicare": "सिविकेयर",
    "civicReportingPlatform": "नागरिक रिपोर्टिंग प्लेटफॉर्म",
    "yourVoice": "एक बेहतर समुदाय के लिए आपकी आवाज",
    "reportIssue": "मुद्दा रिपोर्ट करें",
    "browseIssues": "मुद्दों को ब्राउज़ करें",
    "viewDetails": "विवरण देखें",
    "loading": "लोड हो रहा है...",
    "error": "त्रुटि",
    "success": "सफलता",
    "cancel": "रद्द करें",
    "save": "सहेजें",
    "submit": "सबमिट करें",
    "search": "खोजें",
    "filter": "फिल्टर",
    "sort": "क्रमबद्ध करें",
    "status": "स्थिति",
    "date": "तारीख",
    "location": "स्थान",
    "description": "विवरण",
    "category": "श्रेणी",
    "actions": "क्रियाएँ",

    // Navigation
    "home": "होम",
    "dashboard": "डैशबोर्ड",
    "myComplaints": "मेरी शिकायतें",
    "communityComplaints": "समुदाय की शिकायतें",
    "complaintsMap": "शिकायतों का नक्शा",
    "analytics": "विश्लेषण",
    "admin": "एडमिन",
    "login": "लॉग इन",
    "signup": "साइन अप",
    "logout": "लॉग आउट",

    // Landing Page
    "welcomeMessage": "सिविकेयर में आपका स्वागत है",
    "heroTitle": "एक बेहतर समुदाय के लिए आपकी आवाज",
    "heroSubtitle": "फोटो सबूत और GPS स्थान के साथ तुरंत नागरिक मुद्दों की रिपोर्ट करें। वास्तविक समय में प्रगति को ट्रैक करें और सभी के लिए एक साफ, सुरक्षित पड़ोस बनाने में मदद करें।",
    "trustedBy": "50,000+ नागरिकों द्वारा विश्वसनीय",
    "photoEvidence": "फोटो सबूत",
    "photoEvidenceDesc": "तेजी से समाधान के लिए छवियों को कैप्चर और अपलोड करें",
    "gpsLocation": "GPS स्थान",
    "gpsLocationDesc": "सटीक रिपोर्टिंग के लिए सटीक स्थान ट्रैकिंग",
    "realTimeUpdates": "वास्तविक समय अपडेट",
    "realTimeUpdatesDesc": "जब आपका मुद्दा हल हो जाए तो अधिसूचना प्राप्त करें",
    "reportAnIssue": "एक मुद्दा रिपोर्ट करें",
    "browseReports": "रिपोर्ट ब्राउज़ करें",
    "viewAllReports": "सभी रिपोर्ट देखें",

    // Dashboard
    "welcomeBack": "वापसी पर स्वागत है",
    "studentDashboard": "छात्र डैशबोर्ड",
    "citizenDashboard": "नागरिक डैशबोर्ड",
    "totalComplaints": "कुल शिकायतें",
    "pending": "लंबित",
    "inProgress": "प्रगति में",
    "resolved": "हल हो गया",
    "thisWeek": "इस सप्ताह",
    "quickActions": "त्वरित कार्य",
    "issueMap": "मुद्दा नक्शा",
    "awaitingResponse": "प्रतिक्रिया का इंतजार",
    "beingAddressed": "संबोधित किया जा रहा है",
    "resolutionRate": "समाधान दर",
    "trackIssues": "अपनी समस्याओं को ट्रैक करें और समुदाय के मामलों के बारे में सूचित रहें",
    "emailRequired": "ईमेल आवश्यक है",
    "invalidEmail": "कृपया एक वैध ईमेल पता दर्ज करें",
    "passwordRequired": "पासवर्ड आवश्यक है",
    "invalidCredentials": "अमान्य ईमेल या पासवर्ड। कृपया अपने क्रेडेंशियल्स जांचें और पुनः प्रयास करें।",
    "connectionError": "प्रमाणीकरण सेवा से कनेक्ट नहीं हो सकता। आपका Supabase प्रोजेक्ट रोका गया या निष्क्रिय हो सकता है। कृपया अपने Supabase डैशबोर्ड की जांच करें और यदि आवश्यक हो तो प्रोजेक्ट को फिर से शुरू करें।",
    "signinError": "साइन इन के दौरान एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    "signInMessage": "कृपया अपने खाते में साइन इन करें।",
    "demoAccounts": "डेमो खाते (उपयोग करने के लिए क्लिक करें):",
    "adminAccount": "एडमिन खाता",
    "citizenAccount": "नागरिक खाता",
    "emailAddress": "ईमेल पता",
    "enterEmail": "अपना ईमेल दर्ज करें",
    "enterPassword": "अपना पासवर्ड दर्ज करें",
    "signingIn": "साइन इन हो रहा है...",
    "copyErrorMessage": "त्रुटि संदेश कॉपी करें",
    "creatingAccount": "खाता बनाया जा रहा है...",
    "alreadyHaveAccount": "क्या आपके पास पहले से खाता है?",
    "signInHere": "यहां साइन इन करें",
    "termsAgreement": "खाता बनाकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत हैं।",
    "dontHaveAccount": "खाता नहीं है?",
    "signUpHere": "यहाँ साइन अप करें",
    "termsAgreement": "साइन इन करके, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत हैं।",
    "citizen": "नागरिक",
    "citizenDescription": "समुदाय की समस्याओं की रिपोर्ट करें और उनका ट्रैक रखें",
    "departmentManager": "विभाग प्रबंधक",
    "departmentManagerDescription": "विभागीय समस्याओं का प्रबंधन करें",
    "fullNameRequired": "पूरा नाम आवश्यक है",
    "fullNameMinLength": "पूरा नाम कम से कम 2 अक्षर का होना चाहिए",
    "passwordMinLength": "पासवर्ड कम से कम 6 अक्षर का होना चाहिए",
    "confirmPasswordRequired": "कृपया अपना पासवर्ड पुष्टि करें",
    "passwordsDoNotMatch": "पासवर्ड मेल नहीं खाते",
    "invalidPhoneNumber": "कृपया एक वैध फोन नंबर दर्ज करें",
    "roleRequired": "कृपया अपनी भूमिका चुनें",
    "userAlreadyExists": "इस ईमेल के साथ एक खाता पहले से मौजूद है। कृपया इसके बजाय साइन इन करें।",
    "signupError": "साइन अप के दौरान एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    "accountCreationFailed": "खाता निर्माण विफल हुआ। कृपया पुनः प्रयास करें।",
    "accountCreatedSigningIn": "🎉 खाता सफलतापूर्वक बनाया गया! साइन इन हो रहा है...",
    "accountCreatedPleaseSignIn": "🎉 खाता सफलतापूर्वक बनाया गया! कृपया अपनी क्रेडेंशियल्स के साथ साइन इन करें।",
    "accountCreatedRedirecting": "🎉 खाता सफलतापूर्वक बनाया गया! आपके डैशबोर्ड पर रीडायरेक्ट हो रहा है...",
    "accountCreatedCheckEmail": "🎉 खाता सफलतापूर्वक बनाया गया! साइन इन करने से पहले कृपया अपना खाता पुष्टि करने के लिए अपना ईमेल जांचें।",
    "unexpectedError": "एक अप्रत्याशित त्रुटि हुई। कृपया पुनः प्रयास करें।",
    "createAccount": "खाता बनाएं",
    "joinCivicHub": "समुदाय की समस्याओं की रिपोर्ट करने और उनका ट्रैक रखने के लिए CivicHub से जुड़ें।",
    "fullName": "पूरा नाम",
    "enterFullName": "अपना पूरा नाम दर्ज करें",
    "emailAddress": "ईमेल पता",
    "enterEmail": "अपना ईमेल दर्ज करें",
    "password": "पासवर्ड",
    "createPassword": "एक पासवर्ड बनाएं",
    "confirmPassword": "पासवर्ड पुष्टि करें",
    "confirmYourPassword": "अपना पासवर्ड पुष्टि करें",
    "phoneNumberOptional": "फोन नंबर (वैकल्पिक)",
    "accountType": "खाता प्रकार",
    "chooseAccountType": "समुदाय में अपनी भूमिका के आधार पर अपना खाता प्रकार चुनें",
    "smsUpdates": "हम आपकी रिपोर्टों के बारे में SMS अपडेट भेजेंगे",
    "success": "सफलता!",
    "signUpError": "साइन अप त्रुटि",
    "copyErrorMessage": "त्रुटि संदेश कॉपी करें",

    // Status
    "submitted": "सबमिट किया गया",
    "inReview": "समीक्षा में",
    "assigned": "सौंपा गया",
    "resolved": "हल हो गया",
    "closed": "बंद",
    "rejected": "अस्वीकार किया गया",

    // Categories
    "roads": "सड़कें",
    "sanitation": "स्वच्छता",
    "utilities": "उपयोगिताएँ",
    "infrastructure": "बुनियादी ढाँचा",
    "safety": "सुरक्षा",
    "environment": "पर्यावरण",
    "other": "अन्य",

    // Login/Signup
    "signIn": "साइन इन करें",
    "signUp": "साइन अप करें",
    "email": "ईमेल",
    "password": "पासवर्ड",
    "confirmPassword": "पासवर्ड की पुष्टि करें",
    "fullName": "पूरा नाम",
    "forgotPassword": "पासवर्ड भूल गए?",
    "dontHaveAccount": "खाता नहीं है?",
    "alreadyHaveAccount": "पहले से खाता है?",
    "signInHere": "यहाँ साइन इन करें",
    "createAccount": "खाता बनाएँ",

    // Footer
    "aboutUs": "हमारे बारे में",
    "contactUs": "हमसे संपर्क करें",
    "privacyPolicy": "गोपनीयता नीति",
    "termsOfService": "सेवा की शर्तें",
    "helpCenter": "सहायता केंद्र",
    "allRightsReserved": "सर्वाधिकार सुरक्षित।",
    "madeWithLove": "भारतीय नागरिकों के लिए ❤️ के साथ बनाया गया",

    // Map
    "mapInstructions": "नक्शा निर्देश",
    "clickMarker": "शिकायत विवरण देखने के लिए किसी भी मार्कर पर क्लिक करें",
    "markersColored": "मार्कर शिकायत स्थिति के अनुसार रंगीन हैं",
    "gpsShown": "प्रत्येक शिकायत के लिए GPS निर्देशांक दिखाए गए हैं",
    "complaintsWithoutLocation": "स्थान डेटा के बिना शिकायतें नीचे सूचीबद्ध हैं",

    // Search and Filter
    "searchComplaints": "शिकायतें खोजें",
    "searchByTitle": "शीर्षक, विवरण या स्थान द्वारा खोजें...",
    "filterByStatus": "स्थिति द्वारा फ़िल्टर करें",
    "allStatus": "सभी स्थिति",
    "sortBy": "इसके अनुसार क्रमबद्ध करें",
    "newestFirst": "नवीनतम पहले",
    "oldestFirst": "सबसे पुराना पहले",
    "byStatus": "स्थिति के अनुसार",
    "byTitle": "शीर्षक के अनुसार",

    // Empty States
    "noComplaints": "अभी तक कोई शिकायत नहीं",
    "noComplaintsDesc": "अपनी पहली नागरिक समस्या रिपोर्ट करके शुरू करें और अपने समुदाय में बदलाव लाएँ।",
    "noComplaintsMatch": "आपके फ़िल्टर से कोई शिकायत मेल नहीं खाती",
    "tryAdjustingFilters": "अपनी खोज या फ़िल्टर मानदंड समायोजित करने का प्रयास करें।",
    "reportFirstIssue": "अपनी पहली समस्या रिपोर्ट करें",

    // GPS
    "gpsCoordinates": "GPS निर्देशांक",
    "latitude": "अक्षांश",
    "longitude": "देशांतर",

    // Time
    "justNow": "अभी अभी",
    "hoursAgo": "घंटे पहले",
    "daysAgo": "दिन पहले",
    "weeksAgo": "सप्ताह पहले",

    // Stats
    "communityImpact": "समुदाय प्रभाव",
    "issuesReported": "रिपोर्ट किए गए मुद्दे",
    "issuesResolved": "हल किए गए मुद्दे",
    "resolutionRate": "समाधान दर",
    "activeCitizens": "सक्रिय नागरिक",

    // Trust Signals
    "trustedCertified": "विश्वसनीय और प्रमाणित प्लेटफॉर्म",
    "governmentCertified": "सरकारी अधिकारियों द्वारा आधिकारिक रूप से मान्यता प्राप्त और प्रमाणित",
    "bestCivicApp": "सर्वश्रेष्ठ नागरिक ऐप 2024",
    "userReviews": "10,000+ उपयोगकर्ता समीक्षाओं पर आधारित",
    "isoCertified": "ISO 27001 प्रमाणित",
    "securityManagement": "सूचना सुरक्षा प्रबंधन",
    "uptime": "99.9% अपटाइम",
    "reliableService": "विश्वसनीय 24/7 सेवा उपलब्धता",
    "whatCitizensSay": "नागरिक क्या कहते हैं",
    "realFeedback": "निवासियों और अधिकारियों से वास्तविक प्रतिक्रिया",
    "dataSafeSecure": "आपका डेटा सुरक्षित और सुरक्षित है",
    "securityProtocols": "हम सख्त डेटा सुरक्षा प्रोटोकॉल का पालन करते हैं",
    "verifiedSecure": "सत्यापित सुरक्षित",
    "regularAudits": "नियमित सुरक्षा ऑडिट और प्रवेश परीक्षण",

    // Language
    "language": "भाषा",
    "english": "English",
    "hindi": "हिंदी",
    "switchToHindi": "हिंदी में स्विच करें",
    "switchToEnglish": "English में स्विच करें",

    // Issue Reporting Form
    "reportAnIssue": "मुद्दा रिपोर्ट करें",
    "reportAnIssueSubtitle": "नागरिक मुद्दों की रिपोर्ट करके अपने समुदाय को बेहतर बनाने में मदद करें",
    "capturingYourLocation": "📍 आपका स्थान कैप्चर कर रहे हैं",
    "detectingCurrentLocation": "रिपोर्टिंग को आसान बनाने के लिए हम स्वचालित रूप से आपका वर्तमान स्थान का पता लगा रहे हैं। इससे अधिकारियों को आपके मुद्दे पर तेजी से प्रतिक्रिया देने में मदद मिलती है।",
    "gpsCoordinatesCaptured": "✅ जीपीएस निर्देशांक कैप्चर हो गए",
    "locationDetectedMessage": "आपके वर्तमान स्थान के निर्देशांक स्वचालित रूप से पता लगाए गए हैं। कृपया नीचे स्थान अनुभाग में विस्तृत पता दर्ज करें।",
    "anonymousReporting": "अनाम रिपोर्टिंग",
    "anonymousReportingMessage": "आप अनाम रूप से रिपोर्ट कर रहे हैं। अपनी रिपोर्ट की स्थिति ट्रैक करने और अपडेट प्राप्त करने के लिए साइन इन करने पर विचार करें।",
    "signingIn": "साइन इन करना",
    "submissionError": "सबमिशन त्रुटि",
    "issueTitle": "मुद्दा शीर्षक",
    "issueTitlePlaceholder": "मुद्दे का संक्षिप्त, वर्णनात्मक शीर्षक",
    "issueTitleDescription": "मुद्दे का सारांश देने वाला स्पष्ट, संक्षिप्त शीर्षक प्रदान करें",
    "issueDescription": "मुद्दा विवरण",
    "issueDescriptionPlaceholder": "मुद्दे का विस्तृत विवरण प्रदान करें, जिसमें यह कब शुरू हुआ, यह आपको कैसे प्रभावित करता है, और कोई अन्य प्रासंगिक जानकारी...",
    "priorityLevel": "प्राथमिकता स्तर",
    "lowPriority": "कम",
    "mediumPriority": "मध्यम",
    "highPriority": "उच्च",
    "lowPriorityDesc": "गैर-तत्काल मुद्दा",
    "mediumPriorityDesc": "मध्यम चिंता",
    "highPriorityDesc": "तत्काल ध्यान की आवश्यकता",
    "contactInformation": "संपर्क जानकारी",
    "fullName": "पूरा नाम",
    "fullNamePlaceholder": "आपका पूरा नाम",
    "emailAddress": "ईमेल पता",
    "emailPlaceholder": "your.email@example.com",
    "phoneNumber": "फोन नंबर",
    "phonePlaceholder": "+1 (555) 123-4567",
    "smsUpdates": "हम आपकी रिपोर्ट की स्थिति के बारे में एसएमएस अपडेट भेजेंगे",
    "submitReport": "रिपोर्ट सबमिट करें",
    "submittingReport": "रिपोर्ट सबमिट हो रही है...",
    "saveDraft": "ड्राफ्ट सहेजें",
    "savingDraft": "सहेजा जा रहा है...",
    "cancel": "रद्द करें",
    "reportSubmittedSuccessfully": "🎉 रिपोर्ट सफलतापूर्वक सबमिट हो गई!",
    "reportSubmittedMessage": "आपका मुद्दा सबमिट हो गया है और समीक्षा की जा रही है। आपको प्रगति के बारे में व्हाट्सएप और एसएमएस अपडेट प्राप्त होंगे।",
    "whatsappConfirmation": "आपके पंजीकृत नंबर पर व्हाट्सएप पुष्टिकरण भेजा गया",
    "reportIdLabel": "रिपोर्ट आईडी:",
    "redirectingToReports": "रिपोर्ट्स सूची पर रीडायरेक्ट हो रहा है...",
    "draftSaved": "ड्राफ्ट सफलतापूर्वक सहेजा गया!",
    "draftSaveFailed": "ड्राफ्ट सहेजने में विफल। कृपया पुनः प्रयास करें।",
    "validationCategoryRequired": "कृपया मुद्दे की श्रेणी चुनें",
    "validationTitleRequired": "मुद्दा शीर्षक आवश्यक है",
    "validationTitleMinLength": "शीर्षक कम से कम 10 अक्षर लंबा होना चाहिए",
    "validationDescriptionRequired": "मुद्दा विवरण आवश्यक है",
    "validationDescriptionMinLength": "विवरण कम से कम 20 अक्षर लंबा होना चाहिए",
    "validationLocationRequired": "स्थान पता आवश्यक है (जीपीएस निर्देशांकों के साथ भी)",
    "validationContactNameRequired": "संपर्क नाम आवश्यक है",
    "validationContactEmailRequired": "संपर्क ईमेल आवश्यक है",
    "validationContactEmailInvalid": "कृपया एक वैध ईमेल पता दर्ज करें",
    "validationContactPhoneRequired": "संपर्क फोन आवश्यक है",
    "submissionFailed": "रिपोर्ट सबमिट करने में विफल। कृपया पुनः प्रयास करें।",
    "unexpectedError": "एक अप्रत्याशित त्रुटि हुई। कृपया पुनः प्रयास करें।",

    // Complaints and Reports
    "myComplaints": "मेरी शिकायतें",
    "trackSubmittedIssues": "अपनी सबमिट की गई सभी समस्याओं को ट्रैक और प्रबंधित करें",
    "searchComplaints": "शिकायतें खोजें",
    "searchByTitleDescLocation": "शीर्षक, विवरण या स्थान द्वारा खोजें...",
    "filterByStatus": "स्थिति द्वारा फ़िल्टर करें",
    "allStatus": "सभी स्थिति",
    "issueId": "मुद्दा आईडी",
    "titleAndLocation": "शीर्षक और स्थान",
    "view": "देखें",
    "noComplaintsFound": "कोई शिकायत नहीं मिली",
    "noComplaintsMessageFiltered": "आपकी वर्तमान खोज मानदंड से कोई शिकायत मेल नहीं खाती। अपने फ़िल्टर समायोजित करने का प्रयास करें।",
    "noComplaintsMessageEmpty": "आपने अभी तक कोई शिकायत सबमिट नहीं की है। अपने समुदाय में मुद्दा रिपोर्ट करके शुरू करें।",
    "showingXOfYComplaints": "{total} में से {countShown} शिकायतें दिखा रहे हैं",
    "loadingComplaints": "आपकी शिकायतें लोड हो रही हैं...",
    "communityComplaints": "समुदाय की शिकायतें",
    "exploreCommunityIssues": "अपने समुदाय में मुद्दों के बारे में सूचित रहने के लिए एक्सप्लोर करें",
    "searchCommunityIssues": "समुदाय मुद्दों को खोजें",
    "allCategories": "सभी श्रेणियाँ",
    "water": "पानी",
    "electricity": "बिजली",
    "open": "खुला",
    "noCommunityComplaintsFound": "कोई समुदाय शिकायत नहीं मिली",
    "noCommunityMessageFiltered": "आपकी वर्तमान खोज मानदंड से कोई शिकायत मेल नहीं खाती। अधिक परिणाम देखने के लिए अपने फ़िल्टर समायोजित करने का प्रयास करें।",
    "noCommunityMessageEmpty": "वर्तमान में कोई समुदाय शिकायत प्रदर्शित करने के लिए नहीं है।",
    "showingXCommunityComplaints": "{count} समुदाय शिकायतें दिखा रहे हैं",
    "loadingCommunityComplaints": "समुदाय शिकायतें लोड हो रही हैं...",
    "publicReports": "सार्वजनिक रिपोर्टें",
    "browseCommunityIssues": "निवासियों द्वारा रिपोर्ट की गई समुदाय मुद्दों को ब्राउज़ और ट्रैक करें",
    "totalReports": "कुल रिपोर्टें",
    "grid": "ग्रिड",
    "map": "नक्शा",
    "noReportsFound": "कोई रिपोर्ट नहीं मिली",
    "noReportsMessageFiltered": "अधिक परिणाम देखने के लिए अपने फ़िल्टर समायोजित करने का प्रयास करें।",
    "noReportsMessageEmpty": "अभी तक कोई रिपोर्ट सबमिट नहीं की गई है।",
    "reportAnIssue": "मुद्दा रिपोर्ट करें",
    "issueNotFound": "मुद्दा नहीं मिला",
    "issueNotFoundMessage": "आप जो मुद्दा ढूंढ रहे हैं वह मौजूद नहीं है या हटा दिया गया है।",
    "goBack": "वापस जाएं",
    "browseAllReports": "सभी रिपोर्ट ब्राउज़ करें",
    "description": "विवरण",
    "images": "छवियां",
    "updates": "अपडेट",
    "location": "स्थान",
    "reporter": "रिपोर्टर",
    "assignedDepartment": "नियुक्त विभाग",
    "shareIssue": "मुद्दा साझा करें",
    "reportSimilarIssue": "समान मुद्दा रिपोर्ट करें",
    "home": "होम",
    "reports": "रिपोर्टें",
    "issueDetails": "मुद्दा विवरण",
    "imageNotAvailable": "छवि उपलब्ध नहीं",
    "uploaded": "अपलोड किया गया",
    "priority": "प्राथमिकता",
    "low": "कम",
    "medium": "मध्यम",
    "high": "उच्च",
    "critical": "गंभीर",
    "sortBy": "इसके अनुसार क्रमबद्ध करें",
    "newest": "नवीनतम",
    "oldest": "सबसे पुराना",
    "mostVoted": "सबसे अधिक वोट प्राप्त",
    "loadingReports": "रिपोर्टें लोड हो रही हैं...",
    "errorLoadingReports": "रिपोर्टें लोड करने में त्रुटि",
    "viewDetails": "विवरण देखें"
  }
};

const LanguageContext = createContext();

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('civicare-language');
    if (savedLanguage && ['en', 'hi'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('civicare-language', language);
  }, [language]);

  const t = (key, defaultValue = '') => {
    return translations[language]?.[key] || translations.en[key] || defaultValue || key;
  };

  const switchLanguage = (newLanguage) => {
    if (['en', 'hi'].includes(newLanguage)) {
      setLanguage(newLanguage);
    }
  };

  const value = {
    language,
    t,
    switchLanguage,
    isHindi: language === 'hi',
    isEnglish: language === 'en'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;